config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'emergency_transfer_summary#index'

  resources :emergency_transfer_summary, only: [:show]
end

app/models/admission.rb
class Admission < ApplicationRecord
  belongs_to :patient
  has_many :diagnoses
  has_many :symptoms
  has_many :observations
end

app/models/allergy.rb
class Allergy < ApplicationRecord
  belongs_to :patient
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord
  belongs_to :admission
  belongs_to :patient
end

app/models/diagnostic_procedure.rb
class DiagnosticProcedure < ApplicationRecord
  belongs_to :patient
end

app/models/facility.rb
class Facility < ApplicationRecord
end

app/models/medication_order.rb
class MedicationOrder < ApplicationRecord
  enum mass_unit: ["mg"]
  enum medication_route: ["PO", "IM", "SC"]

  belongs_to :patient
  has_one :frequency, class_name: 'OrderFrequency'
end

app/models/observation.rb
class Observation < ApplicationRecord
  belongs_to :admission
end

app/models/order_frequency.rb
class OrderFrequency < ApplicationRecord
  enum frequency_unit: ["hour"]

  belongs_to :medication_order
end

app/models/patient.rb
class Patient < ApplicationRecord
  enum gender: ["male", "female", "other"]
  
  has_one :admission
  has_many :allergies
  has_many :chronic_conditions, class_name: 'Diagnosis'
  has_many :diagnostic_procedures
  has_many :diagnoses
  has_many :treatments
  has_many :medication_orders

  def full_name
    "#{self.first_name} #{self.middle_name} #{self.last_name}"
  end

  def age
    if self.dob.present?
      age = Date.today.year - self.dob.year
      age -= 1 if Date.today < self.dob.year + age.years
    else
      'DOB not reported'
    end
  end
end

app/models/symptom.rb
class Symptom < ApplicationRecord
  belongs_to :admission
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  belongs_to :patient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/emergency_transfer_summary_controller.rb
class EmergencyTransferSummaryController < ApplicationController

  def index
    @facility = Facility.find_by(name: 'Saint Bernard')
    @patients = Patient.all.order('last_name ASC')
  end

  def show
    @facility = Facility.find_by(name: 'Saint Bernard').name
    @patient = Patient.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emergency_transfer_summary_helper.rb
module EmergencyTransferSummaryHelper
  def to_sentence(patient_attribute, attribute_name)
    attribute_descriptions = patient_attribute&.map do |attribute|
      description = attribute.description&.downcase&.tr('.', '')
      if attribute.has_attribute?(:necessity) && attribute.necessity.present?
        necessity = "to #{attribute.necessity&.downcase&.tr('.', '')}"
      end
      moment = date_sentence(attribute.moment) if attribute.has_attribute?(:moment)
      sentence = "#{description} #{necessity || ""} #{moment}"
      sentence.strip
    end
    attribute_descriptions.all?(&:present?) ? attribute_descriptions.join(', ') : "no #{attribute_name} reported"
  end

  def date_sentence(moment)
    moment.present? ? "on #{moment.strftime('%B %d, %Y')} at #{moment.strftime('%I:%M %p')}" : "no date or time reported"
  end

  def medications(patient_medication_orders)
    medication_orders_data = patient_medication_orders.map do |order|
      "#{order&.name} #{order&.dosage} #{order&.mass_unit} #{order&.medication_route} #{order&.frequency&.value} 
        #{order&.frequency&.frequency_unit.present? ? "per" + order&.frequency&.frequency_unit : ""} 
        #{order.necessity.present? ? "to" + order.necessity : ""}"
    end
    medication_orders_data.all?(&:present?) ? medication_orders_data.join(', ') : "no medication orders reported"
  end
end

app/views/emergency_transfer_summary/index.html.erb
<div class='text-center'>
  <h1><%= @facility.name %></h1>
    <table class="btn-group">
    <tr>
      <th>Patient's Name</th>
      <th>Action(s)</th>
    </tr>
    <% @patients.each do |patient| %>
      <tr>
        <td>
          <%= patient.full_name %>
        </td>
        <td>
          <%= link_to 'View Emergency Transfer Summary', emergency_transfer_summary_path(patient.id) %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/emergency_transfer_summary/show.html.erb
<div class='container'>
  <%= link_to 'Back to View All Patients', root_path %>
  <div class='border'>
    <div class='gray-background'>
      <h2 class='header'>Emergency Transfer Summary (Form 34L-D)</h2>
    </div>
    <div>
      <h3 class='header'>Transferring Facility</h3>
    </div>
    <div class='small-width'>
      <p>Name</p>
      <p><%= @facility %></p>
    </div>
    <div class='border-top'>
      <h3 class='header'>Patient Information</h3>
    </div>
    <div class='flex'>
      <div class='border-right'>
        <p>First Name</p>
        <p><%= @patient.first_name %></p>
      </div>
      <div class='border-right'>
        <p>Middle Name</p>
        <p><%= @patient.middle_name %></p>
      </div>
      <div class='border-right'>
        <p>Last Name</p>
        <p><%= @patient.last_name %></p>
      </div>
      <div class='border-right'>
        <p>Medical Record (MR)</p>
        <p><%= @patient.mr %></p>
      </div>
    </div>
    <div>
      <h3 class='header'>Summary</h3>
    </div>
    <div>
      <p>
        This <%= @patient.age %> years old <%= @patient.gender %> was admitted to <%= @facility %> <%= date_sentence(@patient.admission&.moment) %> due to <%= to_sentence(@patient.admission&.diagnoses, "diagnoses") %>.
        The observed symptoms on admission were <%= to_sentence(@patient.admission&.symptoms, "symptoms") %>. <%= to_sentence(@patient.admission&.observations, "observations").capitalize %>.
      </p>
      <p>
        Upon asking about known allergies, the patient disclosed <%= to_sentence(@patient.allergies, "allergies") %>. Upon asking about chronic conditions, the patient disclosed
        <%= to_sentence(@patient.chronic_conditions, "chronic conditions") %>. The patient was administered with <%= medications(@patient.medication_orders) %>.
      </p>
      <p>
        The staff performed <%= to_sentence(@patient.diagnostic_procedures, "diagnostic procedures") %>, revealing <%= to_sentence(@patient.chronic_conditions, "chronic conditions") %>. Our team proceeded to <%= to_sentence(@patient.treatments, "treatments") %>.
      </p>
    </div>
  </div>
</div>
<button class='btn btn-primary' id='btn' onclick='window.print();'>Print Me</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KipuCodeChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <% # Bootstrap v3.4.1 %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>

    <% # jQuery (necessary for Bootstrap's JavaScript plugins) %>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>

    <% # Bootstrap v3.4.1 %>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
  </body>
</html>